version: 2.1
orbs:
  maven: circleci/maven@0.0.12
# Define the jobs we want to run for this project
jobs:
  build:
    steps:
      - checkout
      - run: 
        commnad: mvn build
  deploy:
    steps:
      - checkout
      - run: 
        command: mvn deploy -DmuleDeploy

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
