version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: mvn clean package
      - run: mvn deploy -DmuleDeploy 
      

# Orchestrate our job run sequence
